build:
  commands:
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:latest ./nginx
    - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
    - echo "Checking if the web page is accessible..."
    - URL="http://a46c8267f8b5a46e1a8d9e3e87cbe44d-944449116.ap-northeast-1.elb.amazonaws.com/"
    - curl --head --silent --fail $URL > /dev/null
    - |
      if [ $? -eq 0 ]; then
        echo "Test passed: Web page is accessible."
      else
        echo "Test failed: Web page is not accessible."
        exit 1
      fi
    - echo "Checking if the web page contains 'Welcome'..."
    - RESPONSE=$(curl --silent $URL)
    - echo "$RESPONSE" | grep -q "Welcome"
    - |
      if [ $? -eq 0 ]; then
        echo "Test passed: 'Welcome' is present on the page."
      else
        echo "Test failed: 'Welcome' not found on the page."
        exit 1
      fi
