version: 0.2

phases:
  install:
    commands:
      - echo "Installing necessary tools..."
      - sudo yum install -y epel-release   # EPELリポジトリを手動でインストール
      - sudo yum install -y curl
  pre_build:
    commands:
      - echo "Pre-build phase..."
  build:
    commands:
      - echo "Testing access to the website..."
      - curl -I http://a46c8267f8b5a46e1a8d9e3e87cbe44d-944449116.ap-northeast-1.elb.amazonaws.com/
  post_build:
    commands:
      - echo "Build completed"
