version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
      - npx cypress install  # Cypress のインストール
  build:
    commands:
      - echo Running Cypress tests...
      - npx cypress run --headless --browser electron --spec "cypress/e2e/spec.cy.js"  # Cypress テストの実行
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - '**/*'
